/** 
 * Advanced Access Manager: Multisite extension. 
 * Code minified with "Closure Compiler" (https://closure-compiler.appspot.com/home) 
 * Complete source can be found on tht GitHub (https://github.com/aamplugin/multisite-extension)
 */
(function(a){function f(d){a.ajax(aamLocal.ajaxurl,{type:"POST",dataType:"json",data:{action:"aam",sub_action:"Multisite.sync",_ajax_nonce:aamLocal.nonce,data:c.data,offset:d},success:function(b){c.sites>=d?(b=Math.round(d/c.sites*100)+"%",a("#multisite-sync-progress .progress-bar").css("width",b).text(b),f(d+1)):(a("#multisite-sync-progress .progress-bar").css("width","100%").text("100%"),aam.notification("success",aam.__("Sync process has been completed successfully")),location.reload())},error:function(){aam.notification("danger",
aam.__("Application error"))}})}function g(){a("#site-list").DataTable({autoWidth:!1,ordering:!1,dom:"trip",pagingType:"simple",processing:!0,serverSide:!0,ajax:{url:aamLocal.ajaxurl,type:"POST",data:{action:"aam",sub_action:"Multisite.getTable",_ajax_nonce:aamLocal.nonce}},columnDefs:[{visible:!1,targets:[0,1,2,5,6]}],language:{search:"_INPUT_",searchPlaceholder:aam.__("Search Site"),info:aam.__("_TOTAL_ sites(s)"),infoFiltered:""},createdRow:function(d,b){var c=parseInt(b[5])?" <small>main site</small>":
"";aamMultisite.current===b[0]?a("td:eq(0)",d).html("<strong>"+b[3]+"</strong>"+c):a("td:eq(0)",d).html("<span>"+b[3]+"</span>"+c);c=b[4].split(",");var e=a("<div/>",{"class":"aam-row-actions"});a.each(c,function(c,f){switch(f){case "manage":a(e).append(a("<i/>",{"class":"aam-row-action "+(parseInt(b[6])?"icon-link":"icon-cog")+" text-info"}).bind("click",function(){parseInt(b[6])?window.open(b[1],"_blank"):(aamMultisite.current=b[0],aamLocal.url.site=b[1],aamLocal.ajaxurl=b[2],a("#site-list tbody tr strong").each(function(){a(this).replaceWith("<span>"+
a(this).text()+"</span>")}),a("td:eq(0) span",d).replaceWith("<strong>"+b[3]+"</strong>"),a("i.icon-cog",e).attr("class","aam-row-action icon-spin4 animate-spin"),a("i.icon-spin4",e).attr("class","aam-row-action icon-cog text-info"),aam.triggerHook("refresh"))}).attr({"data-toggle":"tooltip",title:aam.__("Manage Site")}));break;case "sync":a(e).append(a("<i/>",{"class":"aam-row-action text-warning icon-arrows-cw"}).bind("click",function(){a("#multisite-sync-modal").modal("show")}).attr({"data-toggle":"tooltip",
title:aam.__("Sync Settings")}))}});a("td:eq(1)",d).html(e)}});a("#multisite-sync-btn").bind("click",function(){a(this).prop("disabled",!0).text(aam.__("Wait..."));a("#multisite-sync-options").hide();a("#multisite-sync-progress .progress-bar").css("width","0%");a("#multisite-sync-step").text(aam.__("collecting information"));a("#multisite-sync-progress").show();a.ajax(aamLocal.ajaxurl,{type:"POST",dataType:"json",data:{action:"aam",sub_action:"Multisite.prepareSync",_ajax_nonce:aamLocal.nonce},success:function(a){c=
a;f(1)},error:function(){aam.notification("danger",aam.__("Application error"))}})})}var c={};a(document).ready(function(){g()})})(jQuery);