<?php if (defined('AAM_KEY')) { ?>
    <div class="metabox-holder main-metabox">
        <div class="postbox">
            <h3 class="hndle">
                <span><?php echo __('Site List', AAM_KEY); ?></span>
            </h3>
            <div class="inside" id="access-manager-inside">
                <div class="aam-postbox-inside">
                    <table id="site-list" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Site ID</th>
                                <th>Site URL</th>
                                <th>Site Ajax URL</th>
                                <th width="80%"><?php echo __('Site Domain', AAM_KEY); ?></th>
                                <th><?php echo __('Action', AAM_KEY); ?></th>
                                <th>Main Site</th>
                                <th>Subdomain</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>

                <div class="modal fade" id="multisite-sync-modal" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-sm" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title"><?php echo __('Multisite Sync', AAM_KEY); ?></h4>
                            </div>
                            <div class="modal-body">
                                <div id="multisite-sync-options">
                                    <p class="aam-info">
                                        <?php echo sprintf(__('You can define what should be synced with other sites with ConfigPress settings. For more information about this please check %sAAM and WordPress Multisite support%s article.', AAM_KEY), '<a href="https://aamplugin.com/help/aam-and-wordpress-multisite-support" target="_blank">', '</a>'); ?>
                                    </p>
                                    <?php if (version_compare(AAM_Core_API::version(), '4.9.3') == -1) { ?>
                                        <p class="aam-notification">
                                            <?php echo __('This feature requires AAM 4.9.3 or higher.', AAM_KEY); ?>
                                        </p>
                                    <?php } else { ?>
                                        <p class="aam-notification">
                                            <?php echo __('During the sync, all existing AAM site settings will be overwritten.', AAM_KEY); ?>
                                        </p>
                                    <?php } ?>
                                </div>

                                <div id="multisite-sync-progress" style="display:none;">
                                    <p class="aam-info">
                                        <?php echo __('Please do not reload the page and wait until operation is 100% completed', AAM_KEY); ?>
                                    </p>
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                            0%
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                <button type="button" class="btn btn-warning" id="multisite-sync-btn"><?php echo __('Sync', AAM_KEY); ?></button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
<?php }